[project]
name = "universal-scraper"

[fetch]
targets = ["https://query1.finance.yahoo.com/v7/finance/quote?symbols=AAPL,MSFT,GOOG"]
timeout_secs = 20

[storage]
backend = "supabase"

[storage.options]
table = "records"